version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./core/data:/app/core/data  # Ensure this matches the path where your CSV files are located
    command: python manage.py runserver 0.0.0.0:8000